Repository uttk/swr-site, pull requests merged in 2021-05, with the labels that each got.

#57 Conditional Fetchingのページを翻訳しました
  pages/docs/conditional-fetching.ja.md
Labels: 校正済み, 翻訳

#58 doc: #26 translate "mutation" page
  pages/docs/mutation.ja.md
Labels: 翻訳

#60 doc: #34 translate "Suspense" page into Japanese
  pages/docs/suspense.ja.mdx
Labels: 翻訳

#62 Change Logのページを翻訳しました
  pages/change-log.ja.mdx
Labels: 翻訳

#63 doc: translate revalidation page
  pages/docs/revalidation.ja.mdx
Labels: 校正済み, 翻訳

#61 Getting Startedのページを翻訳しました
  pages/getting-started.ja.mdx
Labels: 校正済み, 翻訳

#64 doc: translate arguments page
  pages/docs/arguments.ja.md
Labels: 翻訳

#71 SWRのサブタイトルを翻訳
  components/features.js
Labels: 翻訳

#65 doc: translate "Performance" page
  pages/advanced/performance.ja.mdx
Labels: 翻訳

#69 Error Handlingページを翻訳しました
  pages/docs/error-handling.ja.mdx
Labels: 翻訳

#72 サイドメニューを翻訳しました
  pages/advanced/meta.ja.json
  pages/docs/meta.ja.json
  pages/examples/meta.ja.json
  pages/meta.ja.json
Labels: 翻訳

#70 Usage with Next.jsページを翻訳しました
  pages/docs/with-nextjs.ja.md
Labels: 校正済み, 翻訳

#73 doc: translate "pagination" page
  pages/docs/pagination.ja.mdx
Labels: 校正済み, 翻訳

#77 トップページの表記ゆれを修正した
  pages/index.ja.mdx
Labels: 校正

#81 Global Configurationページの表記ゆれを修正した
  pages/docs/global-configuration.ja.md
Labels: 校正

#79 Getting Startedページの表記ゆれを修正した
  pages/getting-started.ja.mdx
Labels: 校正

#83 Error Handlingページの表記ゆれを修正した
  pages/docs/error-handling.ja.mdx
Labels: 校正

#85 Conditional Fetchingページの表記ゆれを修正した
  pages/docs/conditional-fetching.ja.md
Labels: 校正

#87 Pagination ページの表記ゆれを修正した
  pages/docs/pagination.ja.mdx
Labels: 校正

#89 Usage with Next.js ページの表記ゆれを修正した
  pages/docs/with-nextjs.ja.md
Labels: 校正

#91 校正漏れを修正した
  pages/docs/conditional-fetching.ja.md
  pages/index.ja.mdx
Labels: 校正

#93 コンフリクトを解消した
  README.md
  components/features.js
  license.md
  next.config.js
  package.json
  pages/advanced/meta.es-ES.json
  pages/advanced/performance.en-US.mdx
  pages/advanced/performance.es-ES.mdx
  pages/advanced/performance.zh-CN.mdx
  pages/change-log.es-ES.mdx
  pages/docs/arguments.es-ES.md
  pages/docs/conditional-fetching.es-ES.md
  pages/docs/data-fetching.es-ES.mdx
  pages/docs/data-fetching.zh-CN.mdx
  pages/docs/error-handling.es-ES.mdx
  pages/docs/global-configuration.es-ES.md
  pages/docs/meta.es-ES.json
  pages/docs/mutation.es-ES.md
  pages/docs/options.es-ES.mdx
  pages/docs/pagination.es-ES.mdx
  pages/docs/prefetching.es-ES.md
  pages/docs/revalidation.es-ES.mdx
  pages/docs/suspense.es-ES.mdx
  pages/docs/with-nextjs.es-ES.md
  pages/examples/auth.es-ES.mdx
  pages/examples/basic.es-ES.mdx
  pages/examples/error-handling.es-ES.mdx
  pages/examples/infinite-loading.es-ES.mdx
  pages/examples/meta.es-ES.json
  pages/getting-started.es-ES.mdx
  pages/index.es-ES.mdx
  pages/meta.es-ES.json
  theme.config.js
Labels: 新機能の作成・提案

#95 フッター/ヘッダーの情報を翻訳した
  theme.config.js
Labels: 新機能の作成・提案, 翻訳

#99 日本語の翻訳者をREADME.mdに追加した
  README.md
Labels: 新機能の作成・提案

#101 トップページの特徴セクションの表現を修正
  pages/index.ja.mdx
Labels: 翻訳
