Repository uttk/swr-site, pull requests merged in 2021-04, with the labels that each got.

#47 サイトヘッダーのプルダウンから日本語選択できるようにした
  next.config.js
  theme.config.js
Labels: 環境構築

#48 doc: #14 translate "Global Configuration" page
  pages/docs/global-configuration.ja.md
Labels: 校正済み, 翻訳

#50 doc: #16 translate "Data-Fetching" page
  pages/docs/data-fetching.ja.mdx
Labels: 校正済み, 翻訳, 翻訳済み

#54 翻訳するページの日本語Markdown・MDXファイルを作成した
  pages/advanced/meta.ja.json
  pages/advanced/performance.ja.mdx
  pages/change-log.ja.mdx
  pages/docs/arguments.ja.md
  pages/docs/conditional-fetching.ja.md
  pages/docs/error-handling.ja.mdx
  pages/docs/meta.ja.json
  pages/docs/mutation.ja.md
  pages/docs/options.ja.mdx
  pages/docs/pagination.ja.mdx
  pages/docs/prefetching.ja.md
  pages/docs/revalidation.ja.mdx
  pages/docs/suspense.ja.mdx
  pages/docs/with-nextjs.ja.md
  pages/examples/auth.ja.mdx
  pages/examples/basic.ja.mdx
  pages/examples/error-handling.ja.mdx
  pages/examples/infinite-loading.ja.mdx
  pages/examples/meta.ja.json
  pages/getting-started.ja.mdx
  pages/index.ja.mdx
  pages/meta.ja.json
Labels: 新機能の作成・提案

#56 doc: #12 translate "API Options" page
  pages/docs/options.ja.mdx
Labels: 翻訳

#55 トップページを翻訳しました
  pages/index.ja.mdx
Labels: 翻訳
