Repository uttk/swr-site, pull requests merged in 2021-06, with the labels that each got.

#105 Custom Cacheページのサイドメニューの翻訳とMarkdownファイルを追加した
  pages/advanced/cache.ja.md
  pages/advanced/meta.ja.json
Labels: 新機能の作成・提案

#107 doc: #102 translate mutation
  pages/docs/mutation.ja.md
Labels: 校正済み, 翻訳, 翻訳済み

#106 "Cache" ページを翻訳した
  pages/advanced/cache.ja.md
Labels: 校正者募集中, 翻訳, 翻訳済み
